### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by un-lock-me** [gauravshelangia/KerasModel_Android#2]
my model also does not have json, what  should I do?

I just have model.h5 and weights.h5 :|

actually this is the thing that I wanna do 
https://github.com/laviavigdor/twitter-sentiment-analysis

**Comment by gauravshelangia** [comment]
You can save the model as JSON file and model weight as hdf5 (.h5) file. And then simply load the model in **dl4j**. 
To save the model as json file do as follow:
``` 
model = Sequential()  # may be some other model you can use
# save model in json file
model_json = model.to_json()
with open("Model_json", "w") as json_file:
    json_file.write(model_json)
```

**Comment by un-lock-me** [comment]
thanks for your explanations,
one more question related to this, 
in part of your code you used array because it was your input,
 I have to do so? I mean its not just about converting kerass model to json and one other step,?
it needs to work on that a lot , am I right?

**Comment by gauravshelangia** [comment]
Yes, the array is input to the model and you have to do the same because your model is also expecting some vector (array) as input. 
Second, you can import keras model in two ways:
1. model saved as json file and weights as hdf5 (.h5)
2. whole model including weights saved as hdf5 file
Other that this, I don't know if there is another way to do the same.

For more see: https://www.youtube.com/watch?v=Cran8wsZLN4

**Comment by un-lock-me** [comment]
thanks for your explanations, and useful link
